# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-02 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
