# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-02 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personify', '0002_profile_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_famous',
            field=models.BooleanField(default=False),
        ),
    ]
