# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-04 13:37
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('personify', '0003_profile_is_famous'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='personality_flat',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
