# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-04 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personify', '0004_profile_personality_flat'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='social_url',
            field=models.URLField(blank=True, max_length=515, null=True),
        ),
    ]
