# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-04 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personify', '0005_profile_social_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='manually_added',
            field=models.BooleanField(default=False),
        ),
    ]
