# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-05 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personify', '0008_profile_share_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(related_name='_profile_friends_+', to='personify.Profile'),
        ),
    ]
