# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-07 18:33
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('personify', '0010_auto_20160907_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='personality_raw',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
